### ISSUE TITLE
add CI tests for every supplied input file

### ISSUE THREAD

**Issue by villaa** [villano-lab/nrCascadeSim#35]
Currently we only test the most complete 28Si input file provided with `realizeCascades`. We should probably test every provided input file.

**Comment by gerudo7** [comment]
I got this started, but I think we might have to resolve #73 before I can finish this one. I'm having issues generating checksums for travis to check these levelfiles:

`cross_sections_and_abundance.txt`
`cross_sections_and_abundance_and_scaling.txt`
`v3_cross_sections_and_abundance.txt`
`v3_cross_sections_and_abundance_scaling.txt`

Because of memory-related issues - either segmentation violations (see https://app.travis-ci.com/github/villano-lab/nrCascadeSim/jobs/554122783#L6353) or "stack smashing" (see https://app.travis-ci.com/github/villano-lab/nrCascadeSim/jobs/554122787#L7551), depending on the build. I can't replicate the issue locally.

**Comment by villaa** [comment]
@gerudo7 I think we should only test these files:

Si28_ngam_all_cascades_rfmt_sorted.txt
20ne_ngam.txt					
allge_ngam_WFast.txt
allge_ngam_WSlow.txt		
40ar_ngam.txt
v3_natSi.txt

The other ones we can move into a directory in that folder that is like "under-development"
